pipeline {
    
    agent {
        docker {
            image 'node-with-react:v3'
            args '-p 3000:3000'
        }
    }
   
    environment {
        CI = 'true'
    }
    
    stages {
        stage('Clone') {
          steps {
            checkout scmGit(
              branches: [[name: "${params.BRANCH_NAME}"]], 
              extensions: [], 
              userRemoteConfigs: [[
                credentialsId: 'medival', 
                url: 'https://github.com/medival/a428-cicd-labs.git'
              ]]
            )
          }
        }
        stage('Build') {
            steps {
                sh 'npm install --verbose'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Manual Approval') {
            steps {
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
        stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                sh './jenkins/scripts/kill.sh'
                sleep time: 1, unit: 'MINUTES'
            }
        }
    }
}
